### PR TITLE
Update to GDB 10.2

### PR DESCRIPTION
**Pull request by klauer**
Based on #38, I mainly just want to see what happens with the CI after noting the following comment: https://github.com/conda-forge/gdb-feedstock/pull/38#issuecomment-864842647

Feel free to close this if you feel it's just adding to your conda-forge spam, I won't be offended.
Marking as draft for starters.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by klauer** [comment]
Failing on the following:
```
/home/conda/feedstock_root/build_artifacts/gdb_1624575266866/work/gdbserver/../gdbsupport/gdb_proc_service.h:177:50: error: expected constructor, destructor, or type conversion before '(' token
  177 |   __attribute__((visibility ("default"))) typeof (SYM) SYM
      |                                                  ^
/home/conda/feedstock_root/build_artifacts/gdb_1624575266866/work/gdbserver/../gdbsupport/gdb_proc_service.h:193:1: note: in expansion of macro 'PS_EXPORT'
  193 | PS_EXPORT (ps_ptwrite);
      | ^~~~~~~~~
```

From https://sourceware.org/git/?p=binutils-gdb.git;a=patch;h=790f17188a22e722bab9915e1d50307f8cb7c0f9 (https://sourceware.org/bugzilla/show_bug.cgi?id=24805)

**Comment by bilderbuchi** [comment]
[This thread](https://sourceware.org/pipermail/gdb/2020-March/048445.html) suggests that the cxxflag std=c++17 could be to blame, and indeed it can be found in the CI logs.
> g++-10 has as default language -std=gnu++14. By compiling with
-std=c++17 you turn off support for GNU extensions, and typeof is the
extension that's used here.

So guess we need to make the build use -std=gnu++17? No idea how to accomplish this at the moment.

**Comment by phil-blain** [comment]
Hi @klauer, thanks for working on this. I think I would try @bilderbuchi's suggestion:

In build.sh, I would try adding
~~~
export CXXFLAGS="${CXXFLAGS} -std=gnu++14"
~~~

just after that line:

https://github.com/conda-forge/gdb-feedstock/blob/fdad172f5c97511035ca512fb7b33fbb5140f077/recipe/build.sh#L55

(the GDB mailing list thread above seems to say  `-std=gnu++17` also fails).

**Comment by bilderbuchi** [comment]
The problem you are alluding to [seems to have been fixed](https://sourceware.org/bugzilla/show_bug.cgi?id=26187) in gdb last summer. So, I think gnu++17 should also be safe/work.

**Comment by klauer** [comment]
Thanks for the suggestions, @bilderbuchi and @phil-blain. `-std=gnu++17` fixed the linux builds completely, though the OSX builds on Travis remain broken.

[Some failure highlights](https://travis-ci.com/github/conda-forge/gdb-feedstock/jobs/519123000):
```
/Users/travis/miniforge3/conda-bld/gdb_1624575775330/_build_env/bin/../include/c++/v1/algorithm:1503:19:/bin/sh ./libtool  --tag=CC   --mode=compile x86_64-apple-darwin13.4.0-clang -DHAVE_CONFIG_H -I. -I$SRC_DIR/bfd  -DBINDIR='"$PREFIX/bin"' -DLIBDIR='"$PREFIX/lib"' -I. -I$SRC_DIR/bfd -I$SRC_DIR/bfd/../include  -DHAVE_x86_64_mach_o_vec -DHAVE_i386_mach_o_vec -DHAVE_mach_o_le_vec -DHAVE_mach_o_be_vec -DHAVE_mach_o_fat_vec -DHAVE_pef_vec -DHAVE_pef_xlib_vec -DHAVE_sym_vec -I./../intl -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -I$PREFIX/include -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -I$SRC_DIR/bfd/../zlib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/gdb-10.2 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -MT archive64.lo -MD -MP -MF .deps/archive64.Tpo -c -o archive64.lo $SRC_DIR/bfd/archive64.c

 error: no member named '__search' in namespace 'std::__1'

...

/Users/travis/miniforge3/conda-bld/gdb_1624635970301/work/gdbsupport/../gdbsupport/gdb_vecs.h:27:20: error: use of undeclared identifier 'gdb'
```

gnu++17 is supported by - and is in fact the default for - the installed clang 11.1.0, which is why the above fix did not affect the OSX build.

**Comment by bilderbuchi** [comment]
could be something like what's described in this quite old post: https://cplusplusmusings.wordpress.com/2012/07/05/clang-and-standard-libraries-on-mac-os-x/
-- maybe before moving everything to libc++, try to step back to std=gnu++14, and see if that helps?

**Comment by bilderbuchi** [comment]
If this feels like very slow whack-a-mole to you, I can relate - iterating on #42 felt quite similarly :laughing:

**Comment by klauer** [comment]
Whack-a-mole is a good description. 😁  Let's give gnu++14 a try on macOS and see what happens!

**Comment by bilderbuchi** [comment]
That did not help, apparently, so let's go back - based on some [googling](https://stackoverflow.com/questions/60859395/unable-to-compile-c17-with-clang-on-mac-osx), maybe try to add `-stdlib=libstdc++` on macos instead, but I'm basically just blindly trying suggestions now (not a mac person at all).

**Comment by bilderbuchi** [comment]
Another thing could be that we are still dragging fragments of `--std=c++17` (not gnu++17) into the build somehowm according to the logs. On linux, that's not a problem, though? :confused:

**Comment by phil-blain** [comment]
Usually conda-forge uses libc++ on macOS (that's the default  these days). So I don't think we should uses libstdc++. And modern clang with modern libstdc++ is mostly uncharted territory anyway.

What I would try is putting back the pin on libc++ at version 10 but only on macOS.

**Comment by klauer** [comment]
More than happy to try any suggestions here! It's mostly a waiting game with how long CI takes.

A brief search into the libstdc++ suggestion seemed to reflect what @phil-blain mentioned, so I'll give a shot at re-adding the pin from 64201c95e1e120be8e7b07fa38c509b3c1fedd53 and limiting it to `osx`.

**Comment by phil-blain** [comment]
re-adding the pinning did not work; we get solver conflicts. So I don't think that's the way to go.

I tried adding `-D_LIBCPP_DISABLE_AVAILABILITY` after searching for "libc++" on Gitter and finding this: https://gitter.im/conda-forge/conda-forge.github.io?at=5f5bb3445fde567ffa3ede83. But it does not seem to help. I'm kind of at a loss here. 

@isuruf do you have an idea of what is missing ? We get failures in the libc++ headers like:
https://travis-ci.com/github/conda-forge/gdb-feedstock/jobs/519258376#L4420-L4425
~~~
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/agent.cc:20:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/common-defs.h:123:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/ptid.h:35:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/_build_env/bin/../include/c++/v1/functional:512:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/../gdb/Block.h:23:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/../gdb/dictionary.h:26:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/../gdb/symfile.h:24:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/work/gdbsupport/../gdb/symtab.h:23:
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624656007191/_build_env/bin/../include/c++/v1/array:116:
/Users/travis/miniforge3/conda-bld/gdb_1624656007191/_build_env/bin/../include/c++/v1/algorithm:1503:81: error: expected '(' for function-style cast or type construction
    return _VSTD::__search<typename add_lvalue_reference<_BinaryPredicate>::type>
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/travis/miniforge3/conda-bld/gdb_1624656007191/_build_env/bin/../include/c++/v1/algorithm:1503:19: error: no member named '__search' in namespace 'std::__1'
    return _VSTD::__search<typename add_lvalue_reference<_BinaryPredicate>::type>
           ~~~~~~~^
~~~

that's the first C++ file of the build...

**Comment by phil-blain** [comment]
OK I investigated this locally and can reproduce (with `build-locally.py`). It's failing because the header files "block.h" in GDB (in `gdb/`) and "Block.h" in `$OSX_SDK_DIR/MacOSX10.9.sdk//usr/include/Block.h`, the header used for [Apples's "Blocks" language extension](https://en.wikipedia.org/wiki/Blocks_(C_language_extension)), collide since the macOS filesystem is case insensitive. 

It seems the new version of libc++ that is pulled in by the conda-forge build infrastructure includes this change: https://reviews.llvm.org/rG430b00954c674241f16549290ab49cc69f93a431 that makes the `functional` standard library header depend on `Block.h`, at least on macOS, which seems to have  `_LIBCPP_HAS_EXTENSION_BLOCKS` defined by default. 

The full compiler invocation is:
~~~
x86_64-apple-darwin13.4.0-clang++  -DHAVE_CONFIG_H  \
 -I.  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/../include  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/../gdb \
 -I../gnulib/import  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/../gnulib/import  \
 -I..  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/..  \
 -I./../intl  \
 -I../bfd  \
 -I/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/../bfd  -D_FORTIFY_SOURCE=2  \
 -Isystem /Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include \
-mmacosx-version-min=10.9  -Wall -Wpointer-arith -Wno-unused -Wunused-value -Wunused-function -Wno-switch -Wno-char-subscripts -Wempty-body -Wno-sign-compare -Wno-mismatched-tags -Wno-error=deprecated-register -Wsuggest-override -Wdeprecated-copy -Wdeprecated-copy-dtor -Wredundant-move -Wmissing-declarations -Wmissing-prototypes -Wformat -Wformat-nonliteral  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -fmessage-length=0  \
 -Isystem /Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include \
-fdebug-prefix-map=/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work=/usr/local/src/conda/gdb-10.2 -fdebug-prefix-map=/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac=/usr/local/src/conda-prefix -std=gnu++17 -MT agent.o -MD -MP -MF .deps/agent.Tpo -c -o agent.o /Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/agent.cc
~~~

Changing `-I` to `-iquote` for the path `/Users/Philippe/Code/gdb-feedstock/miniforge3/conda-bld/gdb_1624896057850/work/gdbsupport/../gdb` is an ugly  workaround, but I think that the real fix would be to disable the "blocks" extension by adding the  `-fno-blocks` flag, which also works. Let's try that.

**Comment by klauer** [comment]
Looks like you've done it, @phil-blain 😄 Linux and OSX builds are now passing with your most recent commit.

Sorry I wasn't of more help here, but at least it seems to have been an inspiration to push it forward.

**Comment by phil-blain** [comment]
Great! Before merging I’d prefer to clean up the history a bit and add better justifications  to some of the commit messages.

**Comment by bilderbuchi** [comment]
Cool! When this is merged I'll try to add Windows support (#42) based on the fresh master/versions.

**Comment by phil-blain** [comment]
@conda-forge/core: I would like to confirm that adding `-D_LIBCPP_DISABLE_AVAILABILITY` on macOS is the right fix for [this error](https://travis-ci.com/github/conda-forge/gdb-feedstock/jobs/519938682#L5107-L5114) (which I copy here): 
~~~
In file included from /Users/travis/miniforge3/conda-bld/gdb_1624919890661/work/gdb/x86-nat.c:23:
Users/travis/miniforge3/conda-bld/gdb_1624919890661/work/gdb/inferior.h:87:19: error: 'uncaught_exceptions' is unavailable: introduced in macOS 10.12
        unwinding = std::uncaught_exceptions () > 0;
                         ^
/Users/travis/miniforge3/conda-bld/gdb_1624919890661/_build_env/bin/../include/c++/v1/exception:132:63: note: 'uncaught_exceptions' has been explicitly marked unavailable here
_LIBCPP_FUNC_VIS _LIBCPP_AVAILABILITY_UNCAUGHT_EXCEPTIONS int uncaught_exceptions() _NOEXCEPT;
                                                              ^
1 error generated.
~~~

If I understand correctly (based on this comment on Gitter: https://gitter.im/conda-forge/conda-forge.github.io?at=5f5bb3445fde567ffa3ede83), clang assumes the system libc++ is used, but it's not the case here, so it's ok to add that macro, right ?

**Comment by isuruf** [comment]
> If I understand correctly (based on this comment on Gitter: https://gitter.im/conda-forge/conda-forge.github.io?at=5f5bb3445fde567ffa3ede83), clang assumes the system libc++ is used, but it's not the case here, so it's ok to add that macro, right ?

Yes

**Comment by phil-blain** [comment]
Thanks @klauer and @bilderbuchi ! I've added details and cleaned up the branch. I'll merge now.

**Comment by bilderbuchi** [comment]
@phil-blain @klauer great to see this merged, glad to help!

I've rebooted the Windows PR #42 now, I'd appreciate if you could keep an eye on it and help out/guide me if you can.

**Pull request merged**
