### PR TITLE
Bump to v8.3

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

~This is based on #12 and #14 (contains all commits of #12 and https://github.com/conda-forge/gdb-feedstock/pull/14/commits/32f17ef463b5ec8486147d0c27c25027a6d0d9a6 from #14), in the interest of getting a 3.7 build as fast as possible (which was failing on all PRs/commits prior to https://github.com/conda-forge/gdb-feedstock/pull/16/commits/86b4c2f857ae986ff6f3967ac84e6a49eb8c0a2e) and hoping that the gdb version bump might have an influence on getting python 2.7 built successfully (failing on https://github.com/conda-forge/gdb-feedstock/pull/16/commits/1e0418fc4f4eb850dc8f46a0fa0d1e63765cb74b).~

Now that #12 has been merged, this should supersede #14 (unless someone rebases that PR).

### CODE REVIEW

**Comment by h-vetinari** [comment]
Ah, well, worth a try. Ends with the [same error](https://github.com/conda-forge/gdb-feedstock/pull/12#issuecomment-512517707) as in #12.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Should we just drop Python 2.7? We can raise an issue about this for follow-up.

**Comment by h-vetinari** [comment]
> @jakirkham: Should we just drop Python 2.7? We can raise an issue about this for follow-up.

I'm all for it! I asked [the same](https://github.com/conda-forge/gdb-feedstock/pull/12#issuecomment-513205103) in #12.

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Rebased on top of #12.

**Comment by h-vetinari** [comment]
@jakirkham @isuruf 
Unless someone updates #14, this would be ready to bump to 8.3.

**Comment by jakirkham** [comment]
Thanks @h-vetinari

**Pull request merged**
