### PR TITLE
Update to GDB 10.1

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by phil-blain** [comment]
Note that GDB 10.1 is kind of broken on macOS:  https://sourceware.org/bugzilla/show_bug.cgi?id=26861. We should still be able to build it and run our test since we do not add a break point but just run the hello.c executable under GDB control (adding a breakpoint seems to trigger the internal GDB assertion failure).

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by bilderbuchi** [comment]
> Note that GDB 10.1 is kind of broken on macOS: https://sourceware.org/bugzilla/show_bug.cgi?id=26861. We should still be able to build it and run our test since we do not add a break point but just run the hello.c executable under GDB control (adding a breakpoint seems to trigger the internal GDB assertion failure).

@phil-blain this bug was fixed in gdb 10.2 that was released in the meantime, maybe makes sense to bump to that directly?

**Comment by phil-blain** [comment]
Closing as #43 supersedes this one.

**Pull request closed without merging**
