### PR TITLE
add phil-blain as maintainer

### PR DESCRIPTION
**Pull request by phil-blain**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] rerendered

I want to publish some packages to the `testing` label on the conda-forge channel in the context of #23. [@isuruf suggested on gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=5ef51807d65a3b0292add884) that I could do that more easily if I become a maintainer. So here is my request.

@marcelotrevisani @gqmelo

### CODE REVIEW

**Comment by phil-blain** [comment]
(I deal with the SPDX stuff in #23)

**Comment by phil-blain** [comment]
well it looks like `[skip-ci]` does not work...

**Comment by phil-blain** [comment]
I also deal with the Python 3.8 failure in #23.

**Comment by phil-blain** [comment]
@conda-forge-admin, please rerender

**Comment by phil-blain** [comment]
Hi @marcelotrevisani !

I followed the instructions here: https://conda-forge.org/docs/maintainer/updating_pkgs.html#updating-the-maintainer-list but bumping the build number was not mentioned there..

Anwyway as I said, I deal with the Python 3.8 failure in #23. If this failure prevents you from merging this (I would think it does not matter if we don't bump the build number), I can always cherry-pick the relevant commit to this PR...

**Comment by marcelotrevisani** [comment]
Closing this in favor of
https://github.com/conda-forge/gdb-feedstock/pull/27

**Comment by phil-blain** [comment]
Thanks @marcelotrevisani !

**Pull request closed without merging**
